### ISSUE TITLE
RC access in libnetcdf

### ISSUE THREAD

**Issue by visr** [natgeo-wong/NetRC.jl#1]
Hi @natgeo-wong, since I saw this repository pop up, I thought I'd mention this upcoming addition to the netCDF library: https://github.com/Unidata/netcdf-c/pull/2408

Right now we already use an internal version of this API to set things in the RC, without having to go through the file:

https://github.com/Alexander-Barth/NCDatasets.jl/blob/e34e4cb955b886a1b0e2f3ffc419b926bd2defe7/src/netcdf_c.jl#L2142

You can still use the RC file to edit settings as well of course, just wanted to mention that soon you can also set it through the library.

**Comment by natgeo-wong** [comment]
Hi!  So we can set username and password in NCDatasets if we have to?  Is that what is being done?

Sorry was at a conference only had time to get back now.

**Comment by visr** [comment]
Yes indeed. It's not all settled and part of a stable API yet, but this will be possible.
Feel free to close the issue, it's just an FYI.

**Comment by natgeo-wong** [comment]
Alright, thanks for the info!
